name = "Introduction à Hydra"
description = "Trouvez le mot de passe du serveur FTP!"
url_name = "hydra"
instructions = """
# Hydra
[Hydra](https://github.com/vanhauser-thc/thc-hydra) est un logiciel libre permettant de craquer un mot de passe en ligne par **bruteforce**.

## Installation
*Cet outils est déjà installé sur la VM d'attaque, cette explication est simplement à but éducatif.*

### Sous Linux
On peut l'installer via **apt-get** ou **snap** :
```
$ sudo apt-get update
$ sudo apt-get install hydra -y
```

### Sous Windows
Passez par [Cygwin](https://www.cygwin.com/) qui est une bibliothèque de logiciels libres permettant d&#39;émuler un système Linux sous différentes versions de Windows.

# Utilisation
"""
victim_vm_ids = [121]


[[question]]
prompt = "Quel était le mot de passe du serveur FTP"
answer = "hannah"
points = 5

[[question]]
prompt = "Avec quel outils graphique (très populaire) peut-on se connecter au serveur FTP?"
answer = "filezilla"
points = 3

[[question]]
prompt = "Donnez le flag caché dans le fichier `flag.txt` sur le serveur"
answer = "r4ti0-au_M@x"
points = 5

