name = "Room 1"
description = "Apprenez à casser des mots de passe !"
url_name = "john"
instructions = """
# John the Ripper
[John the Ripper](https://www.openwall.com/john/) (JTR ou John) est un logiciel libre permettant de tester la sécurité d&#39;un mot de passe.

## Installation
*Cet outils est déjà installé sur la VM d&#39;attaque, cette explication est simplement à but éducatif.*

### Sous Linux
On peut l&#39;installer via **apt-get** ou **snap** :
```
$ sudo apt-get update
$ sudo apt-get install john -y
```

### Sous Windows
Passez par [Cygwin](https://www.cygwin.com/) qui est une bibliothèque de logiciels libres permettant d&#39;émuler un système Linux sous différentes versions de Windows.
Voici un petit guide : `https://miloserdov.org/?p=4961#15`

# Utilisation
Les commandes principales sont :
`john --wordlist=&lt;/path/to/wordlist/wordlists.txt&gt;`

## Les 3 différents modes
### Mode simple (Single crack)
En mode simple, john se génère des variations de chaînes de caractères en fonction du nom d&#39;utilisateur présent dans le fichier. Si le nom d&#39;utilisateur est &#34;voiture&#34;, le mode simple va tester les mots de passe suivants : &#34;Voiture&#34;, &#34;VOIRTURE2000&#34;, &#34;voiTure&#34;, ...

Le contenu du fichier doit être sous la forme `username:hash`.
Exemple :
    `jardinier:a69c316fbc7ec7da1305e72f95c164a8`

La commande doit spécifier le paramètre `--single` ainsi que le format du hash :
`john --single --format=&lt;hash-format&gt; &lt;filename&gt;`


### Attaque par dictionnaire (Wordlist)
L&#39;attaque par dictionnaire test le hash avec tout les mots de passe présents dans une liste de mots (de passe) aussi appelée **wordlist**.

Une des plus célèbre est RockYou, elle est issue d&#39;une fuite de donnée du réseau social californien Rockyou en 2009.

Wordlist : `https://github.com/danielmiessler/SecLists`

`john --wordlist=&lt;/path/to/wordlist&gt;` --format=&lt;hash-format&gt; &lt;filename&gt;`

### Mode incrémental (Incremental)
Dans ce mode, John essaie tout les combinaisons de caractères possible pour trouver le mot de passe.

Spécifier que l&#39;on veut utiliser que des chiffres :
`john -i=&lt;MODE&gt; --format=&lt;hash-format&gt; &lt;filename&gt;`
Exemple :
`john --incremental=digits --format=raw-md5 pass.txt`

### Astuces
John à besoin qu'on lui spécifie un fichier qui contient le hash pour fonctionner.

Avec la machine virtuelle Kali Linux, vous pouvez créer un fichier et coller le hash souhaité à l'aide du 
"""
victim_vm_ids = []

[[question]]
prompt = """;Quel est le mot de passe correspondant au hash suivant (sha256): *4cffb4ed84e2986f067c9e373ef87bf6d5eddc7866fb2cdd41eb48429743f50d*. Utilisez le mode simple."""
answer = "ludovic4000"
points = 3

[[question]]
prompt = """Quel est le mot de passe correspondant au hash suivant (sha1): *26e2440a5730bccb5cf325e8856ac3c38fae9273*. Utilisez la méthode incremental en mode **digits**"""
answer = "52821071"
points = 3

[[question]]
prompt = """Quel est le mot de passe correspondant au hash suivant (md5): *117735823fadae51db091c7d63e60eb0*. Utilisez l&#39;attaque via la wordlist **rockyou**"""
answer = "francisco"
points = 3