name = "Room 5"
description = "lorem ipsum dolor sit amet"
url_name = "room5"
instructions = "QCM"
victim_vm_ids = [  ]

[[question]]
prompt = "Nullpo"
answer = "gah"
points = 5

[[question]]
prompt = "Quel est la réponse a la vie?"
answer = "42"
points = 5